### ISSUE TITLE
Support re-issuance transactions

### ISSUE THREAD

**Issue by tiero** [vulpemventures/liquidjs-lib#27]

**Comment by Janaka-Steph** [comment]
When I confirm a remint the Tx has 2 inputs, one with issuance field undefined, one with issuance field set.
`writeIssuances` loops over the inputs. First one is the input without issuance field. `00` is wrote in Buffer and `this.offset` is incremented from 0 to 1. 
Then it's the turn of the second input. Buffer starts writing at 1 instead of 0. We end up with a `out of bounds` error at the end.

**Comment by Janaka-Steph** [comment]
![Screenshot 2021-09-29 at 13 25 43](https://user-images.githubusercontent.com/4022128/136005999-d1b81d75-1aa3-4238-abb9-69f6edba6977.png)
